version: "3.8"
services:
  nbblackbox_main:
    depends_on:
      nbblackbox_postgres:
        condition: service_healthy
    ports:
      - "80:80"
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      NBBB_DB_HOST: "database"
      NBBB_DB_PASSWD: "secret"
      NBBB_DB_USER: "grader"
      OIDC_RP_CLIENT_ID: "dbis-nbgrader-blackbox"
      OIDC_RP_CLIENT_SECRET: "KYUvsLeAzJMEyOKw8kwr96HROjdoDAbP"
      OIDC_RP_SIGN_ALGO: "RS256"
      OIDC_OP_JWKS_ENDPOINT: "https://auth.las2peer.org/auth/realms/main/protocol/openid-connect/certs"
      OIDC_OP_AUTHORIZATION_ENDPOINT: "https://auth.las2peer.org/auth/realms/main/protocol/openid-connect/auth"
      OIDC_OP_TOKEN_ENDPOINT: "https://auth.las2peer.org/auth/realms/main/protocol/openid-connect/token"
      OIDC_OP_USER_ENDPOINT: "https://auth.las2peer.org/auth/realms/main/protocol/openid-connect/userinfo"
      OIDC_OP_LOGOUT_ENDPOINT: "https://auth.las2peer.org/auth/realms/main/protocol/openid-connect/logout"
      OIDC_OP_LOGOUT_URL_METHOD: "portal.views.keycloak_logout"
      EMAIL_HOST: "smarthost.rwth-aachen.de"
      NBBB_DEBUG: "true"
      NBBB_ALLOWED_HOSTS: "*"
      RED_PERCENTAGE: "0.5"
      YELLOW_PERCENTAGE: "0.7"
      REQUEST_TIME_LIMIT: "300"
      LANGUAGE_CODE: "en"
    networks:
      - nbblackbox_database
  nbblackbox_postgres:
    image: postgres:16
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "grader"
    networks:
      nbblackbox_database:
        aliases:
          - "database"
  nbworker:
    build:
      context: "."
      dockerfile: "DockerfileWorker"
    depends_on:
      nbblackbox_main:
        condition: service_healthy
      nbblackbox_postgres:
        condition: service_started
    volumes:
      - "./testdata/source:/course/source"
    image: nbworker:local
    networks:
      - nbblackbox_database
    environment:
      POSTGRES_HOST: "database"
      POSTGRES_USER: "grader"
      POSTGRES_PASSWORD: "secret"
  landing_page:
    build: 
      context: "."
      dockerfile: "DockerfileLanding"
    ports:
      - "3000:3000" 
    image: landing_page:local
    
networks:
  nbblackbox_database:
