# Generated by Django 5.0 on 2023-12-20 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cell",
            table="cell",
        ),
        migrations.AlterModelTable(
            name="exercise",
            table="exercise",
        ),
        migrations.AlterModelTable(
            name="notebook",
            table="notebook",
        ),
        migrations.AlterModelTable(
            name="subexercise",
            table="subexercise",
        ),
    ]
