# Generated by Django 5.0 on 2024-01-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0002_alter_cell_table_alter_exercise_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingprocess",
            name="notified",
            field=models.BooleanField(
                db_column="notified", default=False, verbose_name="User Notified"
            ),
        ),
    ]
