# Generated by Django 5.0 on 2024-06-20 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0003_gradingprocess_notified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="max_score",
            field=models.FloatField(
                db_column="max_score",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="points",
            field=models.FloatField(db_column="points"),
        ),
    ]
