# Generated by Django 5.1.3 on 2025-01-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_alter_cell_max_score_alter_grading_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='data',
            field=models.BinaryField(db_column='data', default=b''),
            preserve_default=False,
        ),
    ]
