# Generated by Django 5.1.3 on 2025-01-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_add_notebook_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_column='last_updated', verbose_name='Exercise last updated'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='released',
            field=models.BooleanField(db_column='released', default=False, verbose_name='Generated and released by nbgrader'),
        ),
    ]
