# Generated by Django 5.1.3 on 2025-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0006_add_last_updated_and_released_in_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='released',
        ),
        migrations.AddField(
            model_name='notebook',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, db_column='uploaded_at'),
        ),
    ]
