# Generated by Django 5.1.3 on 2025-03-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0007_remove_flag_add_uploaded_date_notebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakSession',
            fields=[
                ('keycloak_sid', models.CharField(db_column='keycloak_sid', max_length=255, primary_key=True, serialize=False)),
                ('django_sid', models.CharField(db_column='django_sid', max_length=40)),
            ],
            options={
                'db_table': 'keycloak_session',
            },
        ),
    ]
