# Generated by Django 5.1.3 on 2025-05-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0008_keycloaksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='assets',
            field=models.BinaryField(blank=True, db_column='assets', null=True),
        ),
    ]
