# Generated by Django 5.1.3 on 2025-06-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0009_notebook_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyContingent',
            fields=[
                ('user_email', models.EmailField(db_column='user_email', max_length=254, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True, db_column='date')),
                ('count', models.IntegerField(db_column='count', default=0)),
            ],
            options={
                'db_table': 'daily_contingent',
            },
        ),
        migrations.AlterField(
            model_name='studentnotebook',
            name='process',
            field=models.OneToOneField(db_column='process', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grader.gradingprocess'),
        ),
    ]
