# Generated by Django 5.1.3 on 2025-07-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0010_dailycontingent_alter_studentnotebook_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="release_data",
            field=models.BinaryField(blank=True, db_column="release_data", null=True),
        ),
    ]
