# Generated by Django 5.1.3 on 2025-09-17 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("grader", "0011_notebook_release_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLimit",
            fields=[
                (
                    "user_id",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("limit", models.IntegerField(db_column="limit", default=10)),
            ],
            options={
                "db_table": "daily_limit",
            },
        ),
        migrations.DeleteModel(
            name="DailyContingent",
        ),
    ]
