[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "nbworker"
version = "0.1"
dependencies = [
    "pika==1.3.2",
    "nbgrader==0.9.1"
]
requires-python = ">= 3.10"
[project.scripts]
nbworker = "nbworker:cmd"