"""
Django settings for nbblackbox project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from os import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+$y%c8zle#gry7(aj$fj^*%_(uubho(+w9%ibph#h#hic&4b00"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    'mozilla_django_oidc', # the oidc auth app
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "grader"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "nbblackbox.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "nbblackbox.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
   # "default": {
   #     "ENGINE": "django.db.backends.sqlite3",
   #     "NAME": BASE_DIR / "db.sqlite3",
   # }
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "grader",
        "USER": "grader",
        "PASSWORD": "secret",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = (
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    # necessary for logging in via local admin password
    'django.contrib.auth.backends.ModelBackend'
)

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "CET"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

OIDC_RP_CLIENT_ID = "dbis-nbgrader-blackbox"
OIDC_RP_CLIENT_SECRET = "KYUvsLeAzJMEyOKw8kwr96HROjdoDAbP"

# AUTH endpoint with hint to only use the rwth aachen login provider
#OIDC_RP_SIGN_ALGO="RS256"
OIDC_OP_AUTHORIZATION_ENDPOINT = "https://auth.las2peer.org/auth/realms/main/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = "https://auth.las2peer.org/auth/realms/main/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = "https://auth.las2peer.org/auth/realms/main/protocol/openid-connect/userinfo"
# necessary to show only rwth sso
OIDC_AUTH_REQUEST_EXTRA_PARAMS={"kc_idp_hint":"rwth-aachen"}
LOGIN_REDIRECT_URL = "/grade/request"

#leave the not Debug pull down to force user auth in non-debug deployment
ALLOW_ANONYMOUS_GRADING = False
NEED_GRADING_AUTH = (not DEBUG) or (not ALLOW_ANONYMOUS_GRADING)
